FROM ubuntu:latest

RUN apt update && apt upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3.10 git curl libmysqlclient-dev build-essential python3.10-dev -y
RUN curl -sSL https://install.python-poetry.org | python3.10  -
RUN git clone https://github.com/AnswerConsulting/AnswerKing-Python --branch develop
WORKDIR AnswerKing-Python
ENV PATH="${PATH}:/root/.local/bin"
RUN poetry install --only main




