version: '3.3'

services:

  database:
    container_name: database
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
    ports:
      - "3306:3306"

  app:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
#    image: ghcr.io/answerconsulting/answerking-python:latest

    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
    ports:
      - "8000:8000"
    expose:
      - "8000"
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
