# Generated by Django 4.1.2 on 2022-10-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answerking_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="calories",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="stock",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
