# Generated by Django 4.1.2 on 2022-11-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answerking_app", "0002_alter_category_name_alter_item_calories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="retired",
            field=models.BooleanField(default=False),
        ),
    ]
